import React, { useState } from 'react';
import { View, Text, StyleSheet, Pressable, Platform, Dimensions } from 'react-native';
import { useColors } from '@/hooks/useColors';
import { useSimulation } from '@/contexts/SimulationContext';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Ionicons, MaterialCommunityIcons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import Animated, { FadeIn, FadeOut } from 'react-native-reanimated';

const STEPS = [
  {
    step: 1,
    icon: 'egg-outline' as const,
    iconSet: 'Ionicons' as const,
    title: 'Step 1: You Buy a Virtual Hen',
    description: 'You invest virtual coins expecting daily egg income. This is the entry point of the scheme.',
    bg: 'normal' as const,
  },
  {
    step: 2,
    icon: 'chart-line' as const,
    iconSet: 'MaterialCommunityIcons' as const,
    title: 'Step 2: Daily Income Arrives',
    description: 'Your dashboard shows growing egg income each day. Looks great, right?',
    bg: 'normal' as const,
  },
  {
    step: 3,
    icon: 'people-outline' as const,
    iconSet: 'Ionicons' as const,
    title: 'Step 3: New Investors Stream In',
    description: 'The scheme grows as more people invest, drawn by the same promises of easy returns.',
    bg: 'normal' as const,
  },
  {
    step: 4,
    icon: 'cash-outline' as const,
    iconSet: 'Ionicons' as const,
    title: 'Step 4: Old Investors Get Payouts',
    description: 'Early investors see payouts — funded NOT by egg sales, but by money from new investors.',
    bg: 'normal' as const,
  },
  {
    step: 5,
    icon: 'warning-outline' as const,
    iconSet: 'Ionicons' as const,
    title: 'THE REVEAL: There Are No Eggs',
    description:
      'These returns were NEVER generated by hens. New investor money flows directly to old investors. There is no underlying product.',
    bg: 'warning' as const,
  },
  {
    step: 6,
    icon: 'trending-down-outline' as const,
    iconSet: 'Ionicons' as const,
    title: 'Step 6: Growth Stalls',
    description: "The scheme can't find new recruits. Growth flatlines. The scheme starts running out of money.",
    bg: 'normal' as const,
  },
  {
    step: 7,
    icon: 'ban-outline' as const,
    iconSet: 'Ionicons' as const,
    title: 'Step 7: Payouts Freeze',
    description: "When new money stops, payouts stop. Investors can't withdraw. Balances are frozen.",
    bg: 'normal' as const,
  },
  {
    step: 8,
    icon: 'alert-circle-outline' as const,
    iconSet: 'Ionicons' as const,
    title: 'Scheme Collapsed',
    description:
      'All Ponzi schemes end this way. No new investors = no money to pay existing ones. Most investors lose everything.',
    bg: 'danger' as const,
  },
];

export default function FlowScreen() {
  const colors = useColors();
  const insets = useSafeAreaInsets();
  const router = useRouter();
  const { resetSimulation } = useSimulation();
  const [currentStep, setCurrentStep] = useState(0);

  const step = STEPS[currentStep];
  const isLast = currentStep === STEPS.length - 1;

  const handleNext = () => {
    if (currentStep < STEPS.length - 1) {
      setCurrentStep(prev => prev + 1);
    }
  };

  const handlePrev = () => {
    if (currentStep > 0) {
      setCurrentStep(prev => prev - 1);
    }
  };

  const handleRestart = () => {
    resetSimulation();
    router.push('/(tabs)/');
  };

  const bgColor =
    step.bg === 'warning'
      ? colors.warning + '15'
      : step.bg === 'danger'
      ? colors.destructive + '15'
      : colors.background;

  return (
    <View style={[styles.container, { backgroundColor: bgColor }]}>
      <View
        style={[
          styles.content,
          { paddingTop: Platform.OS === 'web' ? 67 + 40 : insets.top + 40 },
          { paddingBottom: Platform.OS === 'web' ? 34 + 40 : insets.bottom + 40 },
        ]}
      >
        <View style={styles.progressContainer}>
          {STEPS.map((_, i) => (
            <View
              key={i}
              style={[
                styles.progressDot,
                { backgroundColor: i === currentStep ? colors.primary : colors.border },
              ]}
            />
          ))}
        </View>

        <Animated.View key={currentStep} entering={FadeIn.duration(300)} exiting={FadeOut.duration(200)} style={styles.stepContent}>
          <View
            style={[
              styles.iconContainer,
              {
                backgroundColor:
                  step.bg === 'warning'
                    ? colors.warning + '30'
                    : step.bg === 'danger'
                    ? colors.destructive + '30'
                    : colors.primary + '20',
              },
            ]}
          >
            {step.iconSet === 'Ionicons' ? (
              <Ionicons
                name={step.icon as any}
                size={64}
                color={step.bg === 'warning' ? colors.warning : step.bg === 'danger' ? colors.destructive : colors.primary}
              />
            ) : (
              <MaterialCommunityIcons name={step.icon as any} size={64} color={colors.primary} />
            )}
          </View>

          <Text
            style={[
              styles.title,
              {
                color:
                  step.bg === 'warning' ? colors.warning : step.bg === 'danger' ? colors.destructive : colors.foreground,
              },
            ]}
          >
            {step.title}
          </Text>

          <Text style={[styles.description, { color: colors.foreground }]}>{step.description}</Text>

          {step.step === 5 && (
            <View style={[styles.flowDiagram, { backgroundColor: colors.card, borderColor: colors.border }]}>
              <View style={styles.flowRow}>
                <View style={[styles.flowNode, { backgroundColor: colors.primary + '20', borderColor: colors.primary }]}>
                  <Text style={[styles.flowNodeText, { color: colors.primary }]}>New Investor</Text>
                </View>
                <Text style={[styles.flowArrow, { color: colors.foreground }]}>→</Text>
                <View style={[styles.flowNode, { backgroundColor: colors.accent + '20', borderColor: colors.accent }]}>
                  <Text style={[styles.flowNodeText, { color: colors.accent }]}>Your Coins</Text>
                </View>
                <Text style={[styles.flowArrow, { color: colors.foreground }]}>→</Text>
                <View style={[styles.flowNode, { backgroundColor: colors.primary + '20', borderColor: colors.primary }]}>
                  <Text style={[styles.flowNodeText, { color: colors.primary }]}>Old Investor</Text>
                </View>
              </View>
              <View style={[styles.crossOut, { backgroundColor: colors.destructive }]}>
                <Ionicons name="close" size={40} color="#FFFFFF" />
                <Text style={styles.crossOutText}>Real Product / Service</Text>
              </View>
            </View>
          )}

          {step.step === 8 && (
            <View style={styles.finalBlocks}>
              {[
                {
                  icon: 'storefront-outline' as const,
                  title: 'Real Businesses',
                  text: 'Generate revenue from products or services',
                },
                {
                  icon: 'arrow-redo-circle-outline' as const,
                  title: 'Ponzi Schemes',
                  text: 'Pay old investors with new investor money',
                },
                {
                  icon: 'trending-down' as const,
                  title: 'When Growth Stops',
                  text: 'Collapse is inevitable',
                },
                {
                  icon: 'flag-outline' as const,
                  title: 'Red Flag Rule',
                  text: 'Guaranteed returns + no clear business model = danger',
                },
              ].map((block, i) => (
                <View key={i} style={[styles.finalBlock, { backgroundColor: colors.card, borderColor: colors.border }]}>
                  <Ionicons name={block.icon} size={32} color={colors.primary} />
                  <View style={styles.finalBlockContent}>
                    <Text style={[styles.finalBlockTitle, { color: colors.foreground }]}>{block.title}</Text>
                    <Text style={[styles.finalBlockText, { color: colors.mutedForeground }]}>{block.text}</Text>
                  </View>
                </View>
              ))}
            </View>
          )}
        </Animated.View>

        <View style={styles.controls}>
          {currentStep > 0 && (
            <Pressable
              onPress={handlePrev}
              style={({ pressed }) => [
                styles.button,
                styles.buttonSecondary,
                { backgroundColor: colors.secondary, borderColor: colors.border },
                pressed && styles.buttonPressed,
              ]}
            >
              <Text style={[styles.buttonText, { color: colors.secondaryForeground }]}>Previous</Text>
            </Pressable>
          )}

          {!isLast ? (
            <Pressable
              onPress={handleNext}
              style={({ pressed }) => [
                styles.button,
                styles.buttonPrimary,
                { backgroundColor: colors.primary },
                pressed && styles.buttonPressed,
                currentStep === 0 && styles.buttonFull,
              ]}
            >
              <Text style={[styles.buttonText, { color: colors.primaryForeground }]}>Next</Text>
            </Pressable>
          ) : (
            <View style={styles.finalButtons}>
              <Pressable
                onPress={handleRestart}
                style={({ pressed }) => [
                  styles.button,
                  styles.buttonPrimary,
                  { backgroundColor: colors.primary },
                  pressed && styles.buttonPressed,
                ]}
              >
                <Text style={[styles.buttonText, { color: colors.primaryForeground }]}>Restart Simulation</Text>
              </Pressable>
              <Pressable
                onPress={() => router.push('/(tabs)/learn')}
                style={({ pressed }) => [
                  styles.button,
                  styles.buttonSecondary,
                  { backgroundColor: colors.secondary, borderColor: colors.border },
                  pressed && styles.buttonPressed,
                ]}
              >
                <Text style={[styles.buttonText, { color: colors.secondaryForeground }]}>Back to Learn</Text>
              </Pressable>
            </View>
          )}
        </View>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
  },
  progressContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 40,
  },
  progressDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  stepContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 20,
  },
  iconContainer: {
    width: 120,
    height: 120,
    borderRadius: 60,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: 24,
    fontFamily: 'Inter_700Bold',
    textAlign: 'center',
    paddingHorizontal: 20,
  },
  description: {
    fontSize: 16,
    fontFamily: 'Inter_400Regular',
    textAlign: 'center',
    lineHeight: 24,
    paddingHorizontal: 20,
  },
  flowDiagram: {
    padding: 20,
    borderRadius: 16,
    borderWidth: 1,
    marginTop: 20,
    gap: 16,
  },
  flowRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  flowNode: {
    padding: 12,
    borderRadius: 10,
    borderWidth: 2,
  },
  flowNodeText: {
    fontSize: 12,
    fontFamily: 'Inter_700Bold',
  },
  flowArrow: {
    fontSize: 20,
    fontFamily: 'Inter_700Bold',
  },
  crossOut: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    padding: 12,
    borderRadius: 10,
  },
  crossOutText: {
    fontSize: 14,
    fontFamily: 'Inter_700Bold',
    color: '#FFFFFF',
  },
  finalBlocks: {
    gap: 12,
    width: '100%',
    marginTop: 20,
  },
  finalBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
  },
  finalBlockContent: {
    flex: 1,
  },
  finalBlockTitle: {
    fontSize: 15,
    fontFamily: 'Inter_700Bold',
    marginBottom: 4,
  },
  finalBlockText: {
    fontSize: 13,
    fontFamily: 'Inter_400Regular',
    lineHeight: 18,
  },
  controls: {
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 20,
  },
  button: {
    flex: 1,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonPrimary: {},
  buttonSecondary: {
    borderWidth: 1,
  },
  buttonFull: {
    flex: 1,
  },
  buttonPressed: {
    opacity: 0.7,
  },
  buttonText: {
    fontSize: 16,
    fontFamily: 'Inter_700Bold',
  },
  finalButtons: {
    flex: 1,
    gap: 12,
  },
});
